name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set timestamp
      id: timestamp
      run: echo "::set-output name=timestamp::$(date +%s)"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cmatkhan/llfs_rnaseq:${{ steps.timestamp.outputs.timestamp }}
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push to DockerHub
      run: docker push cmatkhan/llfs_rnaseq:${{ steps.timestamp.outputs.timestamp }}
